name: Needs test

on:

  workflow_dispatch:
   inputs:
    exitcode:
        description: 'Type exit code'
        required: true
        default: '0'
        type: string
         
jobs:
  failingjob:
   runs-on: ubuntu-latest
   steps:
     - run: exit '${{ inputs.exitcode }}'

  echojob:
   needs: failingjob
   runs-on: ubuntu-latest
   steps:
     - run: echo "echojob has run"
  
  
  job1:
    needs: echojob
    if: ${{  success() || needs.echojob.result == 'skipped' && !canceled() }}
    runs-on: ubuntu-latest
    steps:
     - run: |
        sleep 120
        echo "job1 has run"
  job2:
    needs: echojob
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
     - run: |
        sleep 30
        echo "job2 has run"
  job3:
    needs: echojob
    if: ${{ needs.echojob.result == 'skipped' }}
    runs-on: ubuntu-latest
    steps:
     - run: |
        sleep 30
        echo "job3 has run"
